CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."


# Defining model
DEFAULT_VIDEO_TOKEN = "<video>"
DEFAULT_VIDEO_TOKEN_1 = "<video1>"
DEFAULT_VIDEO_TOKEN_2 = "<video2>"
DEFAULT_VIDEO_PATCH_TOKEN = "<vid_patch>"
DEFAULT_VIDEO_PATCH_TOKEN_1 = "<vid_patch1>"
DEFAULT_VIDEO_PATCH_TOKEN_2 = "<vid_patch2>"
DEFAULT_VID_START_TOKEN = "<vid_start>"
DEFAULT_VID_END_TOKEN = "<vid_end>"

# Defining model GCC Token
DEFAULT_IMAGE_TOKEN = "<img>"
DEFAULT_IMAGE_TOKEN_1 = "<img1>"
DEFAULT_IMAGE_TOKEN_2 = "<img2>"
DEFAULT_IMAGE_PATCH_TOKEN = "<img_patch>"
DEFAULT_IMAGE_PATCH_TOKEN_1 = "<img_patch1>"
DEFAULT_IMAGE_PATCH_TOKEN_2 = "<img_patch2>"
DEFAULT_IMG_START_TOKEN = "<img_start>"
DEFAULT_IMG_END_TOKEN = "<img_end>"